sections:
  - name: "Complex Systems"
    label: "complex systems, but not computational complexity"
    threshold: 0.8
  - name: "Collective Intelligence"
    label: "collective intelligence"
    threshold: 0.8
  - name: "Reinforcement Learning"
    label: "reinforcement learning"
    threshold: 0.8
  - name: "Holograpic Principle"
    label: "holographic principle"
    threshold: 0.8
  - name: "Quantum Gravity"
    label: "quantum gravity"
    threshold: 0.8
  - name: "Quantum Field Theory"
    label: "quantum field theory"
    threshold: 0.8